AllCops:
  Include:
    - Gemfile
    - Rakefile
  Exclude:
    - bin/**/*
    - vendor/**/*
    - tmp/**/*

CollectionMethods:
  Enabled: false 

Encoding:
  Enabled: false

LineLength:
  Max: 119

Documentation:
  Enabled: false

CaseIndentation:
  Enabled: false

DotPosition:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 20

Blocks:
  Enabled: false 
  Enabled: false 

AlignParameters:
  Enabled: false

IfUnlessModifier:
  Enabled: false 

TrailingComma:
  Enabled: false
